Server:
  Name: stream-voice
  Debug: true

Asr:
  HostUrl: wss://iat-api.xfyun.cn/v2/iat
  Appid: xxx
  ApiSecret: xxx
  ApiKey: xxx

Logger:
  LogFileName: customize_process
  LogFileExt: .log
  LogSavePath: ./log
  MaxSize: 100    #在进行切割之前，日志文件的最大大小（MB为单位）
  MaxAge: 30      #保留旧文件的最大天数
  MaxBackups: 30  #保留旧文件的最大个数
  Compress: false #是否压缩/归档旧文件